Ext.define('CF.store.MisfitType', {
  extend: 'Ext.data.Store',
  model: 'CF.model.MisfitType',
  data: [{
    name: 'time_frequency',
    parameters: [{
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "min_period",
      value: 0.5
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "max_period",
      value: 10.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "wavelet_parameter",
      value: 6.0
    }],
  }, {
    name: 'pyflex',
    parameters: [{
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "min_period",
      value: 0.5
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "max_period",
      value: 10.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "stalta_waterlevel",
      value: 0.1
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "s2n_limit",
      value: 4.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "snr_max_base",
      value: 3.5
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "tshift_acceptance_level",
      value: 2.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "tshift_reference",
      value: 0.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "dlna_acceptance_level",
      value: 0.8
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "dlna_reference",
      value: 0.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "cc_acceptance_level",
      value: 0.7
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      req: true,
      type: "option",
      name: "earth_model",
      options: ["ak135"],
      value: "ak135"
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "min_surface_wave_velocity",
      value: 0.1
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "max_time_before_first_arrival",
      value: 5.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_0",
      value: 1.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_1",
      value: 2.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_2",
      value: 0.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_3a",
      value: 4.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_3b",
      value: 2.5
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_4a",
      value: 2.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_4b",
      value: 6.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      req: true,
      type: "bool",
      name: "check_global_data_quality",
      value: true
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "snr_integrate_base",
      value: 10.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      type: "int",
      name: "noise_start_index",
      value: 0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: false,
      type: "int",
      name: "noise_end_index",
      value: null
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: false,
      type: "int",
      name: "signal_start_index",
      value: null
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: -1,
      req: true,
      type: "int",
      name: "signal_end_index",
      value: -1
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      req: true,
      type: "option",
      name: "window_signal_to_noise_type",
      options: ["amplitude"],
      value: "amplitude"
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      req: true,
      type: "option",
      name: "resolution_strategy",
      options: ["interval_scheduling", "merge"],
      value: "interval_scheduling"
    }],
  }, {
    name: 'pyflex_and_time_frequency',
    parameters: [{
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "min_period",
      value: 0.5
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "max_period",
      value: 10.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "wavelet_parameter",
      value: 6.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "stalta_waterlevel",
      value: 0.1
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "s2n_limit",
      value: 4.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "snr_max_base",
      value: 3.5
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "tshift_acceptance_level",
      value: 2.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "tshift_reference",
      value: 0.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "dlna_acceptance_level",
      value: 0.8
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "dlna_reference",
      value: 0.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "cc_acceptance_level",
      value: 0.7
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      req: true,
      type: "option",
      name: "earth_model",
      options: ["ak135"],
      value: "ak135"
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "min_surface_wave_velocity",
      value: 0.1
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "max_time_before_first_arrival",
      value: 5.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_0",
      value: 1.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_1",
      value: 2.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_2",
      value: 0.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_3a",
      value: 4.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_3b",
      value: 2.5
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_4a",
      value: 2.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "c_4b",
      value: 6.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      req: true,
      type: "bool",
      name: "check_global_data_quality",
      value: true
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      step: 0.1,
      type: "float",
      name: "snr_integrate_base",
      value: 10.0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: true,
      type: "int",
      name: "noise_start_index",
      value: 0
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: false,
      type: "int",
      name: "noise_end_index",
      value: null
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: 0,
      req: false,
      type: "int",
      name: "signal_start_index",
      value: null
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      minValue: -1,
      req: true,
      type: "int",
      name: "signal_end_index",
      value: -1
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      req: true,
      type: "option",
      name: "window_signal_to_noise_type",
      options: ["amplitude"],
      value: "amplitude"
    }, {
      desc: "",
      editable: true,
      group: "Basic",
      req: true,
      type: "option",
      name: "resolution_strategy",
      options: ["interval_scheduling", "merge"],
      value: "merge"
    }],
  }]
});